name: Build SmartHouse
on:
  push:
    branch:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Upload artifacts to be used in next job
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist


